// <auto-generated />
using CommunityServerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityServerAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CommunityServerAPI.Models.BannedWeapon", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Name");

                    b.ToTable("BannedWeapons");
                });

            modelBuilder.Entity("CommunityServerAPI.Models.ServerPlayer", b =>
                {
                    b.Property<ulong>("steamId")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte[]>("stats")
                        .HasColumnType("longblob");

                    b.HasKey("steamId");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
